[target.x86_64-apple-darwin]
linker = "clang"

rustflags = [
    "-Clink-arg=--target=x86_64-apple-darwin",
    "-Clink-arg=-isysroot/project/MacOSX12.0.sdk",
    "-Clink-arg=-mmacosx-version-min=10.9.0",
    "-Clink-arg=-fuse-ld=/usr/bin/ld64.lld-11",
]
